"""Cross-language PRNG verification tests.

Verifies that the Python SplitMix32 PRNG (hdmi_transfer.prng) produces
identical output to the JavaScript implementation (sender.html) for 1028
seeds with 10 outputs each, and that chooseIndices produces matching
degree and index sets for 600 (seed, K) pairs.
"""

import json
import os

from hdmi_transfer.prng import PRNG, choose_indices

# Path to test vectors generated by scripts/generate_vectors.js
VECTORS_PATH = os.path.join(
    os.path.dirname(__file__), "data", "prng_vectors.json"
)


def _load_vectors():
    """Load pre-generated PRNG test vectors from JSON."""
    with open(VECTORS_PATH) as f:
        return json.load(f)


class TestPRNGRawOutputs:
    """Verify Python PRNG matches JS PRNG for 1028 seeds x 10 outputs."""

    def test_prng_raw_outputs_match_js(self):
        """Load prng_vectors.json and verify all 10,280 outputs match."""
        vectors = _load_vectors()
        mismatches = []

        for entry in vectors["prng_outputs"]:
            seed = entry["seed"]
            expected_outputs = entry["outputs"]
            prng = PRNG(seed)

            for i, expected in enumerate(expected_outputs):
                actual = prng.next()
                if actual != expected:
                    mismatches.append(
                        f"seed={seed}, output[{i}]: "
                        f"expected={expected}, got={actual}"
                    )

        assert not mismatches, (
            f"{len(mismatches)} PRNG mismatches:\n"
            + "\n".join(mismatches[:20])
        )


class TestPRNGKnownVectors:
    """Hardcoded known-good vectors as sanity check."""

    def test_prng_known_vectors(self):
        """Verify a few seeds against hardcoded values from research."""
        vectors = {
            1: [
                1580013426, 350525680, 3524174333,
                3011703609, 643872864,
            ],
            42: [
                551831576, 144025891, 322543647,
                3034809370, 908029994,
            ],
            0xDEADBEEF: [
                46217145, 304148291, 1711218402,
                2692075039, 4098511199,
            ],
        }

        for seed, expected_outputs in vectors.items():
            prng = PRNG(seed)
            for i, expected in enumerate(expected_outputs):
                actual = prng.next()
                assert actual == expected, (
                    f"seed={seed}, output[{i}]: "
                    f"expected={expected}, got={actual}"
                )


class TestPRNGFloatRange:
    """Verify next_float() returns values in [0.0, 1.0)."""

    def test_prng_next_float_range(self):
        """For 100 seeds, all next_float() values are in [0.0, 1.0)."""
        for seed in range(100):
            prng = PRNG(seed)
            for _ in range(10):
                val = prng.next_float()
                assert 0.0 <= val < 1.0, (
                    f"seed={seed}: next_float()={val} out of range [0, 1)"
                )


class TestChooseIndices:
    """Verify chooseIndices determinism and correctness.

    NOTE: The JS cross-language vectors (prng_vectors.json) use the old ad-hoc
    degree distribution.  Python now uses RSD (Phase 5, plan 05-01).  The JS
    sender will be updated to RSD in plan 05-03; cross-language vectors will be
    regenerated at that point.  Until then, we verify determinism directly.
    """

    def test_choose_indices_deterministic(self):
        """Same (seed, K) always returns the same frozenset."""
        for seed in range(1, 50):
            for K in [1, 2, 5, 10, 20, 50]:
                result_a = choose_indices(seed, K)
                result_b = choose_indices(seed, K)
                assert result_a == result_b, (
                    f"seed={seed}, K={K}: non-deterministic"
                )

    def test_choose_indices_returns_frozenset(self):
        """choose_indices returns a frozenset (hashable)."""
        result = choose_indices(1, 10)
        assert isinstance(result, frozenset)

    def test_choose_indices_within_range(self):
        """All returned indices are in [0, K)."""
        for seed in range(1, 100):
            for K in [1, 5, 10, 50]:
                indices = choose_indices(seed, K)
                for idx in indices:
                    assert 0 <= idx < K, (
                        f"seed={seed}, K={K}: index {idx} out of range"
                    )

    def test_choose_indices_k1_singleton(self):
        """K=1: always returns frozenset({0})."""
        for seed in range(1, 20):
            assert choose_indices(seed, 1) == frozenset({0})


class TestPRNGEdgeCases:
    """Edge case tests for PRNG behavior."""

    def test_prng_seed_zero(self):
        """PRNG with seed=0 produces non-zero output."""
        prng = PRNG(0)
        first = prng.next()
        assert first != 0, "seed=0 should still produce non-zero output"

    def test_prng_deterministic(self):
        """Two PRNGs with the same seed produce identical sequences."""
        seed = 12345
        prng_a = PRNG(seed)
        prng_b = PRNG(seed)

        for i in range(100):
            a = prng_a.next()
            b = prng_b.next()
            assert a == b, (
                f"Determinism broken at call {i}: {a} != {b}"
            )
