"""Cross-language PRNG verification tests.

Verifies that the Python SplitMix32 PRNG (receiver_fountain.py) produces
identical output to the JavaScript implementation (sender.html) for 1028
seeds with 10 outputs each, and that chooseIndices produces matching
degree and index sets for 600 (seed, K) pairs.
"""

import json
import os

from receiver_fountain import PRNG

# Path to test vectors generated by scripts/generate_vectors.js
VECTORS_PATH = os.path.join(
    os.path.dirname(__file__), "data", "prng_vectors.json"
)


def _load_vectors():
    """Load pre-generated PRNG test vectors from JSON."""
    with open(VECTORS_PATH) as f:
        return json.load(f)


def choose_indices(seed, K):
    """Mirror the chooseIndices logic from sender.html / receiver_fountain.py.

    NOTE: Includes degree cap to min(degree, K) to avoid infinite loop when
    degree > K (known bug in production code, to be fixed in later phase).
    """
    prng = PRNG(seed)
    degree = 1
    r = prng.next_float()
    if r < 0.1:
        degree = 1
    elif r < 0.6:
        degree = 2
    else:
        degree = int(prng.next_float() * min(K, 20)) + 1

    # Cap degree to K to prevent infinite loop
    degree = min(degree, K)

    indices = set()
    while len(indices) < degree:
        indices.add(prng.next() % K)
    return indices


class TestPRNGRawOutputs:
    """Verify Python PRNG matches JS PRNG for 1028 seeds x 10 outputs."""

    def test_prng_raw_outputs_match_js(self):
        """Load prng_vectors.json and verify all 10,280 outputs match."""
        vectors = _load_vectors()
        mismatches = []

        for entry in vectors["prng_outputs"]:
            seed = entry["seed"]
            expected_outputs = entry["outputs"]
            prng = PRNG(seed)

            for i, expected in enumerate(expected_outputs):
                actual = prng.next()
                if actual != expected:
                    mismatches.append(
                        f"seed={seed}, output[{i}]: "
                        f"expected={expected}, got={actual}"
                    )

        assert not mismatches, (
            f"{len(mismatches)} PRNG mismatches:\n"
            + "\n".join(mismatches[:20])
        )


class TestPRNGKnownVectors:
    """Hardcoded known-good vectors as sanity check."""

    def test_prng_known_vectors(self):
        """Verify a few seeds against hardcoded values from research."""
        vectors = {
            1: [
                1580013426, 350525680, 3524174333,
                3011703609, 643872864,
            ],
            42: [
                551831576, 144025891, 322543647,
                3034809370, 908029994,
            ],
            0xDEADBEEF: [
                46217145, 304148291, 1711218402,
                2692075039, 4098511199,
            ],
        }

        for seed, expected_outputs in vectors.items():
            prng = PRNG(seed)
            for i, expected in enumerate(expected_outputs):
                actual = prng.next()
                assert actual == expected, (
                    f"seed={seed}, output[{i}]: "
                    f"expected={expected}, got={actual}"
                )


class TestPRNGFloatRange:
    """Verify next_float() returns values in [0.0, 1.0)."""

    def test_prng_next_float_range(self):
        """For 100 seeds, all next_float() values are in [0.0, 1.0)."""
        for seed in range(100):
            prng = PRNG(seed)
            for _ in range(10):
                val = prng.next_float()
                assert 0.0 <= val < 1.0, (
                    f"seed={seed}: next_float()={val} out of range [0, 1)"
                )


class TestChooseIndices:
    """Verify chooseIndices matches across Python and JS."""

    def test_choose_indices_match_js(self):
        """Load choose_indices vectors and verify all 600 entries match."""
        vectors = _load_vectors()
        mismatches = []

        for entry in vectors["choose_indices"]:
            seed = entry["seed"]
            K = entry["K"]
            expected_indices = set(entry["indices"])

            actual_indices = choose_indices(seed, K)

            if actual_indices != expected_indices:
                mismatches.append(
                    f"seed={seed}, K={K}: "
                    f"expected={sorted(expected_indices)}, "
                    f"got={sorted(actual_indices)}"
                )

        assert not mismatches, (
            f"{len(mismatches)} chooseIndices mismatches:\n"
            + "\n".join(mismatches[:20])
        )


class TestPRNGEdgeCases:
    """Edge case tests for PRNG behavior."""

    def test_prng_seed_zero(self):
        """PRNG with seed=0 produces non-zero output."""
        prng = PRNG(0)
        first = prng.next()
        assert first != 0, "seed=0 should still produce non-zero output"

    def test_prng_deterministic(self):
        """Two PRNGs with the same seed produce identical sequences."""
        seed = 12345
        prng_a = PRNG(seed)
        prng_b = PRNG(seed)

        for i in range(100):
            a = prng_a.next()
            b = prng_b.next()
            assert a == b, (
                f"Determinism broken at call {i}: {a} != {b}"
            )
