"""Shared browser sender assets built from the canonical protocol manifest."""

from __future__ import annotations

from importlib.resources import files
from typing import Final

from hdmi_exfil.core.config import FRAME_TYPE_DATA, FRAME_TYPE_END, FRAME_TYPE_START
from hdmi_exfil.domain.protocol_manifest import get_protocol_manifest

_ASSET_PACKAGE: Final[str] = "hdmi_exfil.interfaces.browser_sender"
_SCRIPT_BODY_PLACEHOLDER: Final[str] = "{{ SCRIPT_BODY }}"


def _read_asset_text(filename: str) -> str:
    return files(_ASSET_PACKAGE).joinpath(filename).read_text(encoding="utf-8")


def render_protocol_javascript() -> str:
    """Render canonical protocol constants for the browser sender."""
    manifest = get_protocol_manifest()

    lines = [
        "// Generated by tools/build_sender_html.py. Do not edit manually.",
        f"const FOUNTAIN_MAGIC = 0x{manifest.fountain.current_magic:04X};",
        f"const FOUNTAIN_HEADER_PRE_CRC = {manifest.fountain.header_pre_crc};",
        f"const FOUNTAIN_HEADER_LEN = {manifest.fountain.header_size};",
        "",
        f"const SEQ_MAGIC = 0x{manifest.sequential.magic:04X};",
        f"const SEQ_HEADER_PRE_CRC = {manifest.sequential.header_pre_crc};",
        f"const SEQ_CRC_SIZE = {manifest.sequential.crc_size};",
        f"const SEQ_HEADER_LEN = {manifest.sequential.header_size};",
        f"const FRAME_TYPE_START = 0x{FRAME_TYPE_START:02X};",
        f"const FRAME_TYPE_DATA = 0x{FRAME_TYPE_DATA:02X};",
        f"const FRAME_TYPE_END = 0x{FRAME_TYPE_END:02X};",
        "",
        "const PROFILES = {",
    ]

    for name, profile in manifest.profiles.items():
        lines.append(
            "  "
            f'{name}: {{ name: "{profile.name}", width: {profile.width}, '
            f"height: {profile.height}, blockSize: {profile.block_size}, "
            f"targetFps: {profile.target_fps} }},"
        )

    lines.extend([
        "};",
        "",
    ])
    return "\n".join(lines)


def render_sender_script_body() -> str:
    """Render the inline JavaScript body for the standalone sender HTML."""
    protocol_js = render_protocol_javascript().rstrip()
    app_js = _read_asset_text("app.js").strip()
    return f"{protocol_js}\n\n{app_js}\n"


def render_sender_html() -> str:
    """Render the standalone sender HTML document."""
    template = _read_asset_text("template.html")
    if _SCRIPT_BODY_PLACEHOLDER not in template:
        raise ValueError("browser sender template is missing the script placeholder")
    return template.replace(_SCRIPT_BODY_PLACEHOLDER, render_sender_script_body().rstrip())


__all__ = [
    "render_protocol_javascript",
    "render_sender_html",
    "render_sender_script_body",
]
